### ISSUE TITLE
Colon missing before initialiser list

### ISSUE THREAD

**Issue by mugwortmugwort** [o-g-sus/JUCE-HEAVY#2]
Is it intentional that when JucePlugin_PreferredChannelConfigurations is defined there is no colon before the apvts initialisation when declaring the HeavyTutorialAudioProcessor constructor? Should it not have 
#else
     :
#endif
before apvts (*this, nullptr, "Parameters", createParameters()), or the colon before the #ifndef, or is this correct?

```HeavyTutorialAudioProcessor::HeavyTutorialAudioProcessor()
#ifndef JucePlugin_PreferredChannelConfigurations
     : AudioProcessor (BusesProperties()
                     #if ! JucePlugin_IsMidiEffect
                      #if ! JucePlugin_IsSynth
                       .withInput  ("Input",  AudioChannelSet::stereo(), true)
                      #endif
                       .withOutput ("Output", AudioChannelSet::stereo(), true)
                     #endif
                       ),
#endif
apvts (*this, nullptr, "Parameters", createParameters())
{
    for (int i=0; i<parameters.size(); i++) {
        apvts.addParameterListener (parameters.at(i), this);
    }
}

**Comment by o-g-sus** [comment]
No, as you can see in the header file, HeavyTutorialAudioProcessor inherits from public juce::AudioProcessor and public juce::AudioProcessorValueTreeState::Listener, which is indicated by a comma and not by a colon.

**Comment by mugwortmugwort** [comment]
Thanks for getting back. I see what you're saying, but when the #ifndef fails it becomes:

```
HeavyTutorialAudioProcessor::HeavyTutorialAudioProcessor()
apvts (*this, nullptr, "Parameters", createParameters())
{
    for (int i=0; i<parameters.size(); i++) {
        apvts.addParameterListener (parameters.at(i), this);
    }
}
```

There is no colon at all before declaring the initialiser list.
